# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 13:26
from __future__ import unicode_literals

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=Posts.models.file_upload_location),
        ),
    ]
